name: proyecto_seri
description: A new Flutter project.
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.15
  collection: 1.16.0
  flutterflow_ui: ^0.1.0+4
  cupertino_icons: ^1.0.2
  cloud_firestore: 4.2.0
  cloud_firestore_platform_interface: 5.9.1
  cloud_firestore_web: 3.1.1
  firebase_auth: 4.2.0
  firebase_auth_platform_interface: 6.11.4
  firebase_auth_web: 5.2.0
  firebase_core: 2.4.0
  firebase_core_platform_interface: 4.5.2
  firebase_core_web: 2.0.2
  auto_size_text: 3.0.0
  cached_network_image: 3.1.0+1
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  google_fonts: 2.2.0
  google_sign_in: 6.0.2
  google_sign_in_android: 6.1.8
  google_sign_in_ios: 5.6.1
  google_sign_in_platform_interface: 2.4.0
  google_sign_in_web: 0.11.0+2
  intl: 0.17.0
  json_path: 0.3.1
  page_transition: 2.0.4
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  provider: ^5.0.0
  shared_preferences: 2.0.11
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  sqflite: 2.2.6
  timeago: 3.1.0
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2



dependency_overrides:
  collection: 1.15.0


dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/lottie_animations/
    - assets/rive_animations/